// Generated by CoffeeScript 1.6.3
(function() {
  var Hello, a, age, foos, foos2, hey, list, obj, objs, splat_me, zip, _i, _j, _len, _len1, _ref,
    __slice = [].slice;

  list = [1, 2, 3, 4, 5];

  objs = [
    {
      foo: "bar"
    }, {
      foo: "baz"
    }
  ];

  for (_i = 0, _len = objs.length; _i < _len; _i++) {
    obj = objs[_i];
    foos = obj.foo;
  }

  foos2 = (function() {
    var _j, _len1, _results;
    _results = [];
    for (_j = 0, _len1 = objs.length; _j < _len1; _j++) {
      obj = objs[_j];
      _results.push(obj.foo);
    }
    return _results;
  })();

  for (_j = 0, _len1 = objs.length; _j < _len1; _j++) {
    obj = objs[_j];
    if (obj.foo !== "bar") {
      foos2 = say_hello(obj.foo);
    }
  }

  a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  a = [1, 2, 3, 4, 5, 6, 7, 8, 9];

  Hello = (function() {
    function Hello(args) {
      this.args = args;
      console.log(this.args);
    }

    Hello.prototype.dummy_hello = function() {
      var hello;
      hello = this;
      return $.ajax("http://www.google.com", {
        success: function(data, textStatus, xhrObj) {
          return console.log(hello);
        }
      });
    };

    Hello.prototype.to_google = function() {
      var _this = this;
      return $.ajax("http://www.google.com", {
        success: function(data, textStatus, xhrObj) {
          return $.ajax("example.com", {
            success: function(data, textStatus, xhrObj) {
              return console.log(_this);
            }
          });
        }
      });
    };

    return Hello;

  })();

  hey = new Hello();

  hey.dummy_hello();

  hey.to_google();

  splat_me = function() {
    var first, rest, second;
    first = arguments[0], second = arguments[1], rest = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
    return console.log(rest);
  };

  age = 24 > 12 ? "older" : "younger";

  a = "";

  if (a != null) {
    a;
  }

  zip = typeof lottery.drawWinner === "function" ? (_ref = lottery.drawWinner().address) != null ? _ref.zipcode : void 0 : void 0;

}).call(this);
